// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlg3gKQWnDTMWsnymtHpCQL92RFNH2hn4',
    appId: '1:1014429908484:web:48b0e9183f4affd81bbf51',
    messagingSenderId: '1014429908484',
    projectId: 'myapplication-236517e3',
    authDomain: 'myapplication-236517e3.firebaseapp.com',
    storageBucket: 'myapplication-236517e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKHu5LztjeGHbJibTUnMiXnP8swLWL9g',
    appId: '1:1014429908484:android:5cdbd72f3604955f1bbf51',
    messagingSenderId: '1014429908484',
    projectId: 'myapplication-236517e3',
    storageBucket: 'myapplication-236517e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2bZWzx2s6T98Vne9BExTKz4INb1_j-ww',
    appId: '1:1014429908484:ios:6d4b117c4e8ff0ff1bbf51',
    messagingSenderId: '1014429908484',
    projectId: 'myapplication-236517e3',
    storageBucket: 'myapplication-236517e3.firebasestorage.app',
    iosBundleId: 'com.example.brandly4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2bZWzx2s6T98Vne9BExTKz4INb1_j-ww',
    appId: '1:1014429908484:ios:6d4b117c4e8ff0ff1bbf51',
    messagingSenderId: '1014429908484',
    projectId: 'myapplication-236517e3',
    storageBucket: 'myapplication-236517e3.firebasestorage.app',
    iosBundleId: 'com.example.brandly4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlg3gKQWnDTMWsnymtHpCQL92RFNH2hn4',
    appId: '1:1014429908484:web:afc6837d4afe46f51bbf51',
    messagingSenderId: '1014429908484',
    projectId: 'myapplication-236517e3',
    authDomain: 'myapplication-236517e3.firebaseapp.com',
    storageBucket: 'myapplication-236517e3.firebasestorage.app',
  );
}
